spring.application.name=tcs-banking-backoffice

# Formato profesional de logs en consola:
# fecha ISO-8601 | nivel | aplicación | hilo | logger | mensaje
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} | %-5level | ${spring.application.name} | [%thread] | %logger{40} | %msg%n
logging.level.root=INFO
logging.level.com.banking.backoffice=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/tcs_bank
spring.datasource.username=admin
spring.datasource.password=123456789
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
server.port=9098
